### ISSUE TITLE
Add e2e test for registering CassandraDatacenters

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/reaper-operator#10]
We need an e2e test to exercise cassandradatacenter_controller.go. The test should minimally do the following:

* Deploy a Reaper instance with a CassandraDatacenter backend
* Register the CassandraDatacenter

It would be nice to also do the following (but not absolutely necessary):

* Deploy and register a second CassandraDatacenter
* Remove the CassandraDatacenter from Reaper via REST API and verify that the CassandraDatacenter is added back

**Comment by burmanm** [comment]
Isn't ``deploy_reaper_test.go`` already doing the first two parts?

The integ test does the latter one's reregistering.

**Comment by jsanda** [comment]
>Isn't deploy_reaper_test.go already doing the first two parts?

Yeah, you are right.

Looking back over the e2e test code, the following might be better:

* Deploy Reaper before Cassandra. `deploy_reaper_test.go` waits for the CassandraDatacenter to become ready before deploying Reaper
    * Verify Reaper reaches ready state
* Deploy a second CassandraDatacenter that has the reaper annotation and that is not Reaper's backend
    * Verify the Cassandra cluster is registered with Reaper
* Remove Cassandra cluster from Reaper
    * Verify the cluster gets added back

Thoughts?
