### ISSUE TITLE
CI/CD integration for automated e2e/integration testing

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/reaper-operator#14]
Is your feature request related to a problem? Please describe.
The project is currently lacking automated execution of e2e/integration tests.

Describe the solution you'd like
Provide an automated approach to the execution of the existing e2e/integration tests in a publicly visible and available fashion. Preferably via GH actions.

Describe alternatives you've considered
Other CI/CD tools might be possible, such as CircleCI.

Additional context
This issue might need to be clarified or split up into multiple issues to target specific types of tests or integration approaches.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-149) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-149
┆Priority: Medium

**Comment by Miles-Garnsey** [comment]
@jdonenine I think this ticket should probably have been closed a while back? Is there anything in it that wouldn't have been fixed by either #80 or earlier PRs?

**Comment by bradfordcp** [comment]
Closing as it looks like this was resolved in #80
