### ISSUE TITLE
Add or update an e2e test to verify auto scheduling

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/reaper-operator#18]
#17 added initial support for enabling auto scheduling. It would be good to have test coverage to verify that auto scheduling is actually set up. This can be done via Reaper's REST API. We will need to add onto the API in reaper-client-go for this.

Having this test coverage will be important as we build out more functionality around auto scheduling.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-147) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-147
┆Priority: Medium

**Comment by adejanovski** [comment]
Closing this ticket as the work on reaper-operator is now done within k8ssandra-operator.
