### ISSUE TITLE
Add support for Cassandra authentication

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/reaper-operator#28]
**Is your feature request related to a problem? Please describe.**
We want to enable configuration C* authentication. For Reaper that requires specifying credentials for Reaper to use.

**Describe the solution you'd like**
The following changes are needed to support C* auth:

* Add property in CRD for specify name of secret with credentials
* Update controller code to mount secret and set necessary env vars
* Add/update unit tests
* Add/update e2e tests

**Describe alternatives you've considered**

**Additional context**

**Comment by jsanda** [comment]
Related to https://github.com/k8ssandra/k8ssandra/issues/151

**Comment by burmanm** [comment]
I guess an alternative would have been that k8ssandra mounts the secret if it is defined there to be used. And controller wouldn't have to think about the secretName, but instead simply check that if `/secrets/cassandra/username` exists, then use it (and `password`). Of course that moves the logic to the k8ssandra, but there it would be a somewhat simple helm templating.

**Comment by jsanda** [comment]
The username/password are passed via environment variables. How would we set those env vars?
