### ISSUE TITLE
Schema should be fully created prior to starting the Reaper pod

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/reaper-operator#56]
Schema migrations on startup of Reaper can take more time than the liveness probe would allow. This will cause the pods to be killed and restarted, which can happen in the middle of a migration. Some DDL statements are not idempotent (such as adding a column) and can put the pod in a loop as subsequent migration attempts will fail consistently.

Creating the whole schema upfront (including the schema migration table content) would ensure the Reaper pod starts quickly on the first run and avoid that behavior.

This could be done through a job or an init container.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-625) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.3.0

**Comment by jsanda** [comment]
I don't think an init container will solve the problem. We would still face the issues with the probes. 

It might also be worth considering changes to the health checks in Reaper. I believe  the same health check is used for both liveness and readiness probes (see [here](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/resources/ReaperHealthCheck.java) for reference). My understanding is that the schema needs to already be applied for that health check to succeed. That makes sense for the readiness probe, but for the liveness check I think it should just be an endpoint that returns a 200.

**Comment by jsanda** [comment]
Adding the bug label because this is definitely unexpected behavior.

**Comment by adejanovski** [comment]
> I don't think an init container will solve the problem. We would still face the issues with the probes.

Since probes are defined on the main containers, the init container could run for as long as it wants without being restarted, right?

> That makes sense for the readiness probe, but for the liveness check I think it should just be an endpoint that returns a 200.

The problem is that the REST endpoints only start being available after all the schema migrations were applied. We don't want any interaction with the database as long as the schema isn't fully up to date.

**Comment by jsanda** [comment]
>I don't think an init container will solve the problem. We would still face the issues with the probes.
>
>>Since probes are defined on the main containers, the init container could run for as long as it wants without being restarted, right?

That is correct. There is another issue though. If we allow multiple replicas of Reaper then we run into concurrent schema modifications.

>The problem is that the REST endpoints only start being available after all the schema migrations were applied. We don't want any interaction with the database as long as the schema isn't fully up to date.

I totally understand that we do not want any interactions with the database until the schema is updated. Even if it just for k8s deployments, we should consider a liveness probe that is not dependent on the database. The fact of the matter is, while those schema updates are getting applied, Reaper _is_ alive.

**Comment by jdonenine** [comment]
Some potential context here:  https://github.com/thelastpickle/cassandra-reaper/issues/956

**Comment by jdonenine** [comment]
The original solution proposed for 956 has some code here:  https://github.com/thelastpickle/cassandra-reaper/pull/957
