### ISSUE TITLE
Need support to enable user authentication for Reaper webui

### ISSUE THREAD

**Issue by zhongshuaiz** [k8ssandra/reaper-operator#59]
**Is your feature request related to a problem? Please describe.**
We need reaper-operator give an interfact to overwrite the REAPER_AUTH_ENABLED env var, so that if we expose reaper webui, it would be more secure.

**Describe the solution you'd like**
Let CRD to support REAPER_AUTH_ENABLED can be overwritten. For now, it's hard coded "false".

┆Issue is synchronized with this [Jiraserver Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-720) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-720
┆Priority: Medium

**Comment by jsanda** [comment]
Closing as won't fix. This is or will be addressed in the k8ssandra-operator repo.
