### ISSUE TITLE
Clean up the config directory

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/reaper-operator#67]
**Is your feature request related to a problem? Please describe.**

The `./config` directory in this project needs to be reviewed and so does the one under `./test/config`.

It is filled with what appears to be cruft created by operator-sdk like [this](https://github.com/k8ssandra/reaper-operator/blob/master/config/samples/reaper_v1alpha1_reaper.yaml). 

Trying to do `kustomize build config/default` results in an error, but should probably produce a Reaper deployment.

Under `test/config` there are a few problems also, for example, where deploy_reaper_test should probably deploy only Reaper, it also deploys CassDCs. This is a good, but it would be more modular (and reusable) if the kustomize.yaml at the top level called one kustomize.yaml for reaper and another kustomize.yaml for the supporting components.

**Describe the solution you'd like**

It would be nice to two kustomize bases - one for Reaper and one for whatever other bits are required for testing (e.g. Cassandra backend and such).

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-837) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-837
┆Priority: Medium

**Comment by Miles-Garnsey** [comment]
Above issue  ^^ talks about whether we should pursue the approach proposed in this ticket, or accept the cruft in the framework in the name of standardisation.

**Comment by jsanda** [comment]
Closing as won't fix
