### ISSUE TITLE
Document reaper-operator

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/reaper-operator#72]
This project has no standalone documentation, and it could probably use some.

Documentation which is focused on k8ssandra is mainly about the helm charts. This repo should probably have a configuration reference for the CRs at least.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-906) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-906
┆Priority: Medium

**Comment by Miles-Garnsey** [comment]
Agreed, noting that if the CR will stay the same we can document that as a starting point (doesn't matter which repo it happens in) with a view to moving the same README under k8ssandra-operator once we pull the controller over.

Dev documentation would be awesome, but even a basic explanation of the CR would be great to surface up somewhere prominent.

**Comment by adejanovski** [comment]
Closing this since work is happening in k8ssandra-operator now
