### ISSUE TITLE
Deployments on k8s v1.22 fail

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/reaper-operator#76]
**Describe the bug**
A number of APIs have been changed/removed in k8s v1.22 and the operator can no longer deploy in those environments.

**To Reproduce**

1. Deploy a kind cluster with node version v1.22.0

```
kind create cluster --image "kindest/node:v1.22.0"
```

1. Build and deploy medusa operator (note that this example won't work fully as it lacks the bucket configuration required but it demonstrates the core issue)

```
kustomize build test/config/dev | kubectl apply -f - 
```

1. Observe the following errors:

```
customresourcedefinition.apiextensions.k8s.io/reapers.reaper.cassandra-reaper.io created
clusterrole.rbac.authorization.k8s.io/cass-operator-cr unchanged
clusterrolebinding.rbac.authorization.k8s.io/cass-operator-crb configured
[unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "STDIN": no matches for kind "CassandraDatacenter" in version "cassandra.datastax.com/v1beta1"]
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
Error from server (NotFound): error when creating "STDIN": namespaces "reaper-dev" not found
```

This error in particular:

```
[unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "STDIN": no matches for kind "CassandraDatacenter" in version "cassandra.datastax.com/v1beta1"]
```

**Expected behavior**
Deployments should work on k8s v1.22 (as well as previous versions - as reasonable)

* Kubernetes version information:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T20:01:24Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
Kind

**Additional context**
This is the partial root cause of https://github.com/k8ssandra/k8ssandra/issues/1127

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-961) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-961
┆Priority: Medium

**Comment by jsanda** [comment]
Need to verify that this has been resolved and then close the ticket.

**Comment by Miles-Garnsey** [comment]
Looking at PR #80 which was merged 11 Nov 2021 it appears that a matrix entry was added in the kuttl tests to test k8s 1.22 [here](https://github.com/k8ssandra/reaper-operator/pull/80/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R121). 

Within the `build.yaml` workflow there is a step `run_kuttl_test` which is still running on every PR to ensure that 1.22 works. At the time the above PR was merged, that test was passing (see [here](https://github.com/k8ssandra/reaper-operator/runs/4174959802?check_suite_focus=true)).

**Comment by bradfordcp** [comment]
Looks like this ticket isn't needed then. Closing.
