### ISSUE TITLE
Add liveness and readiness checks to reaper-operator

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/reaper-operator#78]
reaper-operator's deployment doesn't appear to include liveness or readiness checks at present. We should include these in the deployment and set up an HTTP server in the manager to respond to them appropriately.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1005) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1005
┆Priority: Medium

**Comment by jsanda** [comment]
Closing as won't fix.
