### ISSUE TITLE
Generate images with fixed tags on commits to master

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/reaper-operator#83]
**Is your feature request related to a problem? Please describe.**

Cass-operator and management API CI pipelines both emit tagged images when commits are pushed to master. 

reaper-operator should be brought into line with this practice to make testing possible in downstream repos (e.g. k8ssandra) without referring to a `latest` tag.

**Describe the solution you'd like**

Switch out the `latest` tag currently used in the image push for a sha based hash.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1037) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1037
┆Priority: Medium

**Comment by adejanovski** [comment]
Work takes place in k8ssandra-operator now, which does this already
