### ISSUE TITLE
Add integration test for cassandradatacenter_controller.go

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/reaper-operator#9]
┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-152) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-152
┆Priority: Medium

**Comment by bradfordcp** [comment]
Closing in favor of tests in k8ssandra-operator
